{block content}

{control $filters begin}
<fieldset style="border:1px solid silver; margin-bottom: 1.5em;">
    <legend>Filtry</legend>
    <p>
        {$filters["search"]->label} {$filters["search"]->control}
        {$filters["activeOnly"]->control} {$filters["activeOnly"]->label}
        {$filters["s"]->control}
    </p>
</fieldset>
{control $filters end}

{control grid}

<p><a n:href="Homepage:">Zpět</a></p>

<style type="text/css">
.gridito tr.odd td {
	background: white;
}
.gridito tr.inactive td {
	color: gray;
}
.gridito td.small {
	max-width: 3em;
}
</style>