{block content}

{control grid}

<p><a n:href="Homepage:">Zpět</a></p>

<style type="text/css">
.gridito tr.odd td {
	background: white;
}
.gridito tr.even td {
	background: #FDEBCC;
}
.gridito tr.inactive td {
	color: gray;
}
.gridito td.important {
	font-weight: bold !important;
	color: navy !important;
	font-size: 1.1em;
}
.ui-icon.icon-tick {
	background: url("{$basePath}/images/tick.png");
}
.ui-icon.icon-window {
	background: url("{$basePath}/images/application_get.png");
}
</style>