{block content}

{control grid}

<style type="text/css">
.gridito tr.odd td {
	background: white;
}
.gridito tr.even td {
	background: #FDEBCC;
}
.gridito tr.inactive td {
	color: gray;
}
.gridito td.important {
	font-weight: bold !important;
	color: navy !important;
	font-size: 1.1em;
}
.ui-icon.icon-tick {
	background: url("{$basePath}/images/tick.png");
}
.ui-icon.icon-window {
	background: url("{$basePath}/images/application_get.png");
}
</style>

{/block}

{block code}
{include #parent}
<li><a href="http://github.com/janmarek/Gridito/blob/master/app/models/UsersGriditoDoctrineModel.php">Gridito model</a></li>
<li><a href="http://github.com/janmarek/Gridito/blob/master/app/models/User.php">User entity</a></li>
{/block}