@{block content}

{gridito $control["grid"]}
	{griditocolumn id text => "id", sortable => true}
	{griditocolumn username text => "Username", sortable => true}
	{griditocolumn name text => "Name", sortable => true}
	{griditocolumn surname text => "Surname", sortable => true}
	{griditocolumn mail text => "E-mail", sortable => true}
	{griditocolumn active text => "Active", sortable => true}
{/gridito}