{block content}

<ul>
	<li><a n:href="DibiSimple:">Simple example (dibi)</a>
	<li><a n:href="DoctrineSimple:">Simple example (Doctrine2)</a>
	<li><a n:href="DoctrineButtons:">Buttons example (Doctrine2)</a>
	<li><a n:href="DoctrineCustomRendering:">Custom rendering (Doctrine2)</a>
	<li><a n:href="DibiFilters:">Filters example (dibi)</a>
	<li><a n:href="DoctrineCustomTemplate:">Custom grid template (Doctrine2)</a>
</ul>