{block content}

{control $filters begin}
<fieldset>
    <legend>Filters</legend>
    <p>
        {$filters["search"]->label} {$filters["search"]->control}
        {$filters["activeOnly"]->control} {$filters["activeOnly"]->label}
        {$filters["s"]->control}
    </p>
</fieldset>
{control $filters end}

{control grid}

{/block}

{block code}
{include #parent}
<li><a href="http://github.com/janmarek/Gridito/blob/master/app/models/UsersGriditoDibiModel.php">Gridito model</a></li>
{/block}