<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Gridito example">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>Gridito example</title>

	<!-- jQuery, jQuery UI & livequery -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js" type="text/javascript"></script>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css" type="text/css">

	<!-- Gridito -->
	<link rel="stylesheet" href="{$basePath}/css/gridito.css.php" type="text/css">
	<script type="text/javascript" src="{$basePath}/js/jquery.nette.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.livequery.js"></script>
	<script type="text/javascript" src="{$basePath}/js/jquery.ui.gridito.js.php"></script>

	<script type="text/javascript">
	// gridito init
	$("div.gridito").livequery(function () {
		$(this).gridito();
	});

	// nette ajax init
	$("a.ajax").live("click", function (event) {
		event.preventDefault();
		$.get(this.href);
	});
	</script>

	<link rel="stylesheet" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">
</head>

<body>
	<div id="header">
		<h1>{ifCurrent Homepage:}Gridito examples{else}<a n:href="Homepage:">Gridito examples</a>{/ifCurrent}</h1>
		<p>Datagrid for <a href="http://nette.org/">Nette Framework</a></p>
	</div>
	
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	<div id="content">
	{include #content}

	{ifCurrent Homepage:}{else}
	<h2 class="section-heading">Source code</h2>
	<ul>
		{block code}
		<li><a href="http://github.com/janmarek/Gridito/blob/master/app/presenters/{$control->getName()}Presenter.php">Presenter</a></li>
		<li><a href="http://github.com/janmarek/Gridito/blob/master/app/templates/{$control->getName()}/default.phtml">View template</a></li>
		{/block}
	</ul>
	<p class="section-heading"><a n:href="Homepage:">Back</a></p>
	{/ifCurrent}
	</div>
</body>
</html>
