<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Gridito example">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>Gridito example</title>

	<!-- jQuery, jQuery UI & livequery -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" type="text/javascript"></script>
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css" type="text/css">
	<script type="text/javascript" src="{$basePath}/js/jquery.livequery.js"></script>

	<!-- Gridito -->
	<link rel="stylesheet" href="{$basePath}/css/gridito.css" type="text/css">
	<script type="text/javascript" src="{$basePath}/js/gridito.js"></script>

	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">
</head>

<body>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	@{include #content}
</body>
</html>
